// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgiJhqYj_w13O8XMshO9qmoquP2xRLsLs',
    appId: '1:993795916855:android:8dc862a1b7fefee66c6bb2',
    messagingSenderId: '993795916855',
    projectId: 'projeto-z-fb0cd',
    databaseURL: 'https://projeto-z-fb0cd-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-z-fb0cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZqi1L4PnLod79BY3iIV5ov5USlpwGfBw',
    appId: '1:993795916855:ios:cff674f4bc86c6026c6bb2',
    messagingSenderId: '993795916855',
    projectId: 'projeto-z-fb0cd',
    databaseURL: 'https://projeto-z-fb0cd-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-z-fb0cd.appspot.com',
    iosClientId: '993795916855-eqvolgsdakvrd06jrvcrnoejhc0t7k9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.teste1',
  );
}
